(()=>{'use strict';
const KEY='globalNewsLanguage',CACHE='gn-final-i18n-v18:',RTL=new Set(['ar','ur','fa']);
const SUPPORTED=new Set(['en','zh','hi','es','fr','ar','bn','pt','ru','ur','id','de','ja','mr','te','tr','ta','vi','ko','it','fa']);
const STATIC={
fr:{Home:'Accueil','🇮🇳 India':'Inde','IN India':'Inde',India:'Inde',World:'Monde',Geopolitics:'Géopolitique','International Relations':'Relations internationales',Business:'Affaires',Technology:'Technologie',Entertainment:'Divertissement',Sports:'Sports',Science:'Science',Climate:'Climat',Search:'Rechercher','Read full story →':'Lire l’article →','Back to stories':'Retour aux actualités','Story Brief':'Résumé de l’article','Full Report':'Rapport complet','Sources & attribution':'Sources et attribution','Related Stories':'Articles connexes','Translate this story':'Traduire cet article','Most Spoken Languages in the World':'Langues les plus parlées au monde','Explore Worldwide':'Explorer le monde','Regions & countries':'Régions et pays',Country:'Pays','Top Stories · Worldwide':'Principales actualités · Monde','Live news':'Actualités en direct','Fact-checked':'Vérifié','Unbiased Reporting':'Information impartiale','Updated Regularly':'Mis à jour régulièrement','Powered by AI · Translations may not be 100% accurate.':'Propulsé par l’IA · Les traductions peuvent ne pas être exactes à 100 %.','Story Brief is limited for this source.':'Le résumé de cette source est limité.','The publisher did not return enough distinct article text for reliable key points. The headline/lead above and attributed source below remain available.':'L’éditeur n’a pas fourni suffisamment de texte distinct pour établir des points clés fiables. Le titre/résumé ci-dessus et la source attribuée ci-dessous restent disponibles.','Detailed source report is currently unavailable.':'Le rapport détaillé de la source est actuellement indisponible.','The publisher did not return enough distinct article text for a reliable Full Report. No unsupported details are invented.':'L’éditeur n’a pas fourni suffisamment de texte distinct pour un rapport complet fiable. Aucun détail non vérifié n’est inventé.','Open original source ↗':'Ouvrir la source originale ↗'},
hi:{Home:'होम','🇮🇳 India':'भारत','IN India':'भारत',India:'भारत',World:'विश्व',Geopolitics:'भू-राजनीति','International Relations':'अंतरराष्ट्रीय संबंध',Business:'व्यवसाय',Technology:'प्रौद्योगिकी',Entertainment:'मनोरंजन',Sports:'खेल',Science:'विज्ञान',Climate:'जलवायु',Search:'खोजें','Read full story →':'पूरी खबर पढ़ें →','Back to stories':'खबरों पर वापस','Story Brief':'संक्षिप्त विवरण','Full Report':'विस्तृत रिपोर्ट','Sources & attribution':'स्रोत और श्रेय','Related Stories':'संबंधित खबरें','Translate this story':'इस खबर का अनुवाद करें','Most Spoken Languages in the World':'दुनिया में सबसे अधिक बोली जाने वाली भाषाएँ','Explore Worldwide':'दुनिया भर में देखें','Regions & countries':'क्षेत्र और देश',Country:'देश','Top Stories · Worldwide':'शीर्ष खबरें · विश्वभर','Live news':'लाइव खबरें','Fact-checked':'तथ्य-जाँचा हुआ','Unbiased Reporting':'निष्पक्ष रिपोर्टिंग','Updated Regularly':'नियमित रूप से अपडेट','Powered by AI · Translations may not be 100% accurate.':'AI द्वारा संचालित · अनुवाद 100% सटीक न हो सकते हैं।','Search global stories, topics, countries or sources…':'वैश्विक खबरें, विषय, देश या स्रोत खोजें…','Story Brief is limited for this source.':'इस स्रोत के लिए संक्षिप्त विवरण सीमित है।','The publisher did not return enough distinct article text for reliable key points. The headline/lead above and attributed source below remain available.':'प्रकाशक ने विश्वसनीय मुख्य बिंदुओं के लिए पर्याप्त अलग लेख-पाठ उपलब्ध नहीं कराया। ऊपर दिया गया शीर्षक/लीड और नीचे दिया गया स्रोत उपलब्ध है।','Detailed source report is currently unavailable.':'विस्तृत स्रोत रिपोर्ट फिलहाल उपलब्ध नहीं है।','The publisher did not return enough distinct article text for a reliable Full Report. No unsupported details are invented.':'विश्वसनीय पूर्ण रिपोर्ट के लिए प्रकाशक ने पर्याप्त अलग लेख-पाठ उपलब्ध नहीं कराया। कोई असमर्थित विवरण नहीं जोड़ा गया है।','Open original source ↗':'मूल स्रोत खोलें ↗'},
es:{Home:'Inicio','🇮🇳 India':'India','IN India':'India',India:'India',World:'Mundo',Geopolitics:'Geopolítica','International Relations':'Relaciones internacionales',Business:'Negocio',Technology:'Tecnología',Entertainment:'Entretenimiento',Sports:'Deportes',Science:'Ciencia',Climate:'Clima',Search:'Buscar','Read full story →':'Leer la historia completa →','Back to stories':'Volver a las noticias','Story Brief':'Resumen de la historia','Full Report':'Informe completo','Sources & attribution':'Fuentes y atribución','Related Stories':'Historias relacionadas','Translate this story':'Traducir esta historia','Most Spoken Languages in the World':'Idiomas más hablados del mundo','Explore Worldwide':'Explorar el mundo','Regions & countries':'Regiones y países',Country:'País','Top Stories · Worldwide':'Principales noticias · Mundo','Live news':'Noticias en directo','Fact-checked':'Verificado','Unbiased Reporting':'Información imparcial','Updated Regularly':'Actualizado periódicamente','Powered by AI · Translations may not be 100% accurate.':'Con tecnología de IA · Las traducciones pueden no ser 100 % precisas.','Story Brief is limited for this source.':'El resumen de esta fuente es limitado.','The publisher did not return enough distinct article text for reliable key points. The headline/lead above and attributed source below remain available.':'El editor no proporcionó suficiente texto distinto para obtener puntos clave fiables. El titular/entradilla de arriba y la fuente atribuida de abajo siguen disponibles.','Detailed source report is currently unavailable.':'El informe detallado de la fuente no está disponible actualmente.','The publisher did not return enough distinct article text for a reliable Full Report. No unsupported details are invented.':'El editor no proporcionó suficiente texto distinto para un informe completo fiable. No se inventa ningún detalle no respaldado.','Open original source ↗':'Abrir fuente original ↗'},
ur:{Home:'ہوم','🇮🇳 India':'بھارت','IN India':'بھارت',India:'بھارت',World:'دنیا',Geopolitics:'جغرافیائی سیاست','International Relations':'بین الاقوامی تعلقات',Business:'کاروبار',Technology:'ٹیکنالوجی',Entertainment:'تفریح',Sports:'کھیل',Science:'سائنس',Climate:'آب و ہوا',Search:'تلاش','Read full story →':'مکمل خبر پڑھیں →','Back to stories':'خبروں پر واپس','Story Brief':'مختصر خلاصہ','Full Report':'مکمل رپورٹ','Sources & attribution':'ذرائع اور حوالہ','Related Stories':'متعلقہ خبریں','Translate this story':'اس خبر کا ترجمہ کریں','Most Spoken Languages in the World':'دنیا کی سب سے زیادہ بولی جانے والی زبانیں','Explore Worldwide':'دنیا بھر میں دیکھیں','Regions & countries':'علاقے اور ممالک',Country:'ملک','Story Brief is limited for this source.':'اس ذریعے کے لیے مختصر خلاصہ محدود ہے۔','Detailed source report is currently unavailable.':'تفصیلی سورس رپورٹ فی الحال دستیاب نہیں۔','Open original source ↗':'اصل ذریعہ کھولیں ↗'},
zh:{Home:'首页','🇮🇳 India':'印度','IN India':'印度',India:'印度',World:'世界',Geopolitics:'地缘政治','International Relations':'国际关系',Business:'商业',Technology:'科技',Entertainment:'娱乐',Sports:'体育',Science:'科学',Climate:'气候',Search:'搜索','Read full story →':'阅读完整报道 →','Back to stories':'返回新闻','Story Brief':'新闻摘要','Full Report':'完整报告','Sources & attribution':'来源与归属','Related Stories':'相关新闻','Translate this story':'翻译这篇新闻','Most Spoken Languages in the World':'世界上使用人数最多的语言','Explore Worldwide':'探索全球','Regions & countries':'地区和国家',Country:'国家','Story Brief is limited for this source.':'此来源的新闻摘要有限。','Detailed source report is currently unavailable.':'详细来源报告目前不可用。','Open original source ↗':'打开原始来源 ↗'}
};
const lang=()=>{const v=localStorage.getItem(KEY)||'en';return SUPPORTED.has(v)?v:'en'};
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
function remember(el){if(!el||!el.isConnected)return '';if(!el.dataset.gnFinalOriginal)el.dataset.gnFinalOriginal=clean(el.textContent);return el.dataset.gnFinalOriginal||''}
function split(s,max=560){const out=[];let v=clean(s);while(v.length>max){let i=Math.max(v.lastIndexOf('. ',max),v.lastIndexOf('? ',max),v.lastIndexOf('! ',max),v.lastIndexOf(', ',max));if(i<160)i=max;out.push(v.slice(0,i+1));v=v.slice(i+1).trim()}if(v)out.push(v);return out}
async function server(text,to){const r=await fetch('/api/translate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,to}),cache:'no-store'});if(!r.ok)throw Error('server_'+r.status);const j=await r.json(),v=clean(j?.text);if(!v||v===text)throw Error('empty');return v}
async function browser(text,to){const chunks=split(text),out=[];for(const p of chunks){let v='';try{const r=await fetch('https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl='+encodeURIComponent(to)+'&dt=t&q='+encodeURIComponent(p),{mode:'cors',cache:'no-store'});if(r.ok){const j=await r.json();v=clean((j?.[0]||[]).map(x=>x?.[0]||'').join(''))}}catch(_){}if(!v||v===p){try{const r=await fetch('https://api.mymemory.translated.net/get?q='+encodeURIComponent(p)+'&langpair=en|'+encodeURIComponent(to),{mode:'cors',cache:'no-store'});if(r.ok){const j=await r.json();v=clean(j?.responseData?.translatedText)}}catch(_){} }if(!v||v===p)throw Error('browser_unavailable');out.push(v)}return clean(out.join(' '))}
async function translate(text,to){if(to==='en')return text;const d=STATIC[to]||{};if(d[text])return d[text];const key=CACHE+to+':'+text;try{const hit=localStorage.getItem(key);if(hit)return hit}catch(_){}for(let n=0;n<2;n++){try{const v=await server(text,to);try{localStorage.setItem(key,v)}catch(_){}return v}catch(_){await new Promise(r=>setTimeout(r,100*(n+1)))}}try{const v=await browser(text,to);try{localStorage.setItem(key,v)}catch(_){}return v}catch(_){}throw Error('translation_unavailable')}
const HOME=['.hero h1','.hero p','.hero .read','.card h3','.card p','.card .read'];
const CHROME=['#nav button','#search','.sectionhead h2','.explorer-title','.explorer-title span','.explorer-hint','.country-picker label','.region-row button','.footer','.story-reader-back','.side-title','.ai-side-card h3','.ai-translate-note','.ai-trust','.ai-footer-strip span'];
const STORY=['.story-reader-head h1','.story-reader-head>p','.story-reader-head .badge','.story-reader-head .country-tag','.story-reader-section h2','#storyReaderBrief li','#storyReaderBrief .story-reader-limited','#storyReaderBrief .story-reader-error','#storyReaderReport p','#storyReaderReport .story-reader-label','#storyReaderReport .story-reader-note','#storyReaderReport .story-reader-limited','#storyReaderReport .story-reader-error','.story-reader-source .story-source-title','.story-reader-source strong','.story-reader-source a','.ai-story-meta span'];
const SIDE=['.ai-sidebar .side-title','.ai-sidebar .side-meta','.ai-sidebar .ai-side-card h3','.ai-sidebar .ai-translate-note','.ai-sidebar .ai-trust','.ai-sidebar .ai-footer-strip span'];
function collect(selectors){const out=[];for(const sel of selectors)for(const el of document.querySelectorAll(sel)){if(el.closest('.ai-langs')||!clean(el.textContent))continue;const src=remember(el);if(src)out.push(el)}return [...new Set(out)]}
function restore(){for(const el of document.querySelectorAll('[data-gn-final-original]')){el.textContent=el.dataset.gnFinalOriginal;delete el.dataset.gnStatic}const q=document.querySelector('#q');if(q?.dataset.gnPlaceholderOriginal)q.placeholder=q.dataset.gnPlaceholderOriginal}
function staticApply(to){const d=STATIC[to]||{};for(const el of collect(CHROME)){const src=remember(el);if(d[src]){el.textContent=d[src];el.dataset.gnStatic='1'}}const q=document.querySelector('#q');if(q){if(!q.dataset.gnPlaceholderOriginal)q.dataset.gnPlaceholderOriginal=q.placeholder;const src=q.dataset.gnPlaceholderOriginal;if(d[src])q.placeholder=d[src]}}
let gen=0,timer=0,running=false,pending=false;
async function group(list,to,g){for(let i=0;i<list.length;i+=2){if(g!==gen||lang()!==to)return;await Promise.all(list.slice(i,i+2).map(async el=>{const src=remember(el);if(!src||(STATIC[to]||{})[src])return;try{const v=await translate(src,to);if(g===gen&&lang()===to&&el.isConnected)el.textContent=v}catch(_){}}));await new Promise(r=>setTimeout(r,20))}}
async function apply(){if(running){pending=true;return}running=true;pending=false;const g=++gen,to=lang();document.documentElement.lang=to;document.documentElement.dir=RTL.has(to)?'rtl':'ltr';restore();staticApply(to);await group(collect(CHROME).filter(e=>!e.dataset.gnStatic),to,g);await group(collect(HOME),to,g);await group(collect(STORY).filter(e=>!e.dataset.gnStatic),to,g);await group(collect(SIDE).filter(e=>!e.dataset.gnStatic),to,g);running=false;if(pending||g!==gen||lang()!==to)apply()}
function schedule(ms=60){clearTimeout(timer);timer=setTimeout(apply,ms)}
function start(){schedule(0);window.addEventListener('global-news-language-change',()=>{gen++;schedule(0)});window.addEventListener('global-news-home-rendered',()=>schedule(0));window.addEventListener('global-news-story-content-rendered',()=>schedule(120));window.addEventListener('global-news-sidebar-rendered',()=>schedule(120));new MutationObserver(ms=>{if(running)return;if(ms.some(m=>m.type==='childList'&&m.addedNodes.length))schedule(180)}).observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();