(()=>{'use strict';
const KEY='globalNewsLanguage',CACHE='gn-final-i18n-v6:',RTL=new Set(['ar','ur','fa']);
const SUPPORTED=new Set(['en','zh','hi','es','fr','ar','bn','pt','ru','ur','id','de','ja','mr','te','tr','ta','vi','ko','it','fa']);
const STATIC={hi:{Home:'होम','🇮🇳 India':'भारत','IN India':'भारत',India:'भारत',World:'विश्व',Geopolitics:'भू-राजनीति','International Relations':'अंतरराष्ट्रीय संबंध',Business:'व्यवसाय',Technology:'प्रौद्योगिकी',Entertainment:'मनोरंजन',Sports:'खेल',Science:'विज्ञान',Climate:'जलवायु',Search:'खोजें','Read full story →':'पूरी खबर पढ़ें →','Back to stories':'खबरों पर वापस','Story Brief':'संक्षिप्त विवरण','Full Report':'विस्तृत रिपोर्ट','Sources & attribution':'स्रोत और श्रेय','Related Stories':'संबंधित खबरें','Translate this story':'इस खबर का अनुवाद करें','Most Spoken Languages in the World':'दुनिया में सबसे अधिक बोली जाने वाली भाषाएँ','Explore Worldwide':'दुनिया भर में देखें','Regions & countries':'क्षेत्र और देश',Country:'देश','Top Stories · Worldwide':'शीर्ष खबरें · विश्वभर','Live news':'लाइव खबरें'},ur:{Home:'ہوم','🇮🇳 India':'بھارت','IN India':'بھارت',India:'بھارت',World:'دنیا',Geopolitics:'جغرافیائی سیاست','International Relations':'بین الاقوامی تعلقات',Business:'کاروبار',Technology:'ٹیکنالوجی',Entertainment:'تفریح',Sports:'کھیل',Science:'سائنس',Climate:'آب و ہوا',Search:'تلاش','Read full story →':'مکمل خبر پڑھیں →','Back to stories':'خبروں پر واپس','Story Brief':'مختصر خلاصہ','Full Report':'مکمل رپورٹ','Sources & attribution':'ذرائع اور حوالہ','Related Stories':'متعلقہ خبریں','Translate this story':'اس خبر کا ترجمہ کریں','Most Spoken Languages in the World':'دنیا کی سب سے زیادہ بولی جانے والی زبانیں','Explore Worldwide':'دنیا بھر میں دیکھیں','Regions & countries':'علاقے اور ممالک',Country:'ملک'}};
const lang=()=>{const v=localStorage.getItem(KEY)||'en';return SUPPORTED.has(v)?v:'en'};
const clean=v=>String(v??'').replace(/\s+/g,' ').trim();
const english=v=>/[A-Za-z]{3}/.test(v||'');
const bad=v=>/QUERY LENGTH LIMIT EXCEEDED|MAX ALLOWED QUERY|TRANSLATION FAILED|HTTP\s*4\d\d|translation unavailable/i.test(v||'');
function theme(){if(document.getElementById('gn-final-theme'))return;const s=document.createElement('style');s.id='gn-final-theme';s.textContent='.gn-i18n-pending{opacity:.72;transition:opacity .15s}.story-reader-error,.notice.error{display:block!important}html[dir=rtl] body{direction:rtl;text-align:right}';document.head.appendChild(s)}
function split(text,max=900){const out=[];let s=clean(text);while(s.length>max){let i=Math.max(s.lastIndexOf('. ',max),s.lastIndexOf('? ',max),s.lastIndexOf('! ',max),s.lastIndexOf(', ',max));if(i<250)i=max;out.push(s.slice(0,i+1));s=s.slice(i+1).trim()}if(s)out.push(s);return out}
async function req(text,to){const k=CACHE+to+':'+text;try{const hit=localStorage.getItem(k);if(hit)return hit}catch(_){}let v='';try{const r=await fetch('/api/translate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text,to}),cache:'no-store'});if(r.ok){const j=await r.json();v=clean(j?.text)}}catch(_){}if(!v||bad(v)||v===text){try{const u='https://api.mymemory.translated.net/get?q='+encodeURIComponent(text)+'&langpair=en|'+encodeURIComponent(to);const r=await fetch(u,{cache:'no-store'});if(r.ok){const j=await r.json();v=clean(j?.responseData?.translatedText)}}catch(_){}}if(!v||bad(v)||v===text)throw Error('translation unavailable');try{localStorage.setItem(k,v)}catch(_){}return v}
async function translate(text,to){if(to==='en')return text;const out=[];for(const p of split(text)){try{out.push(await req(p,to))}catch(_){return null}}return out.join(' ')}
const SELECTORS=['.hero h1','.hero p','.hero .read','.card h3','.card p','.card .read','#nav button','#search','.sectionhead h2','.explorer-title','.explorer-title span','.explorer-hint','.country-picker label','.region-row button','.story-reader-head h1','.story-reader-head p','.story-reader-section h2','#storyReaderBrief li','#storyReaderBrief .story-reader-limited','#storyReaderBrief .story-reader-error','#storyReaderReport p','#storyReaderReport .story-reader-label','#storyReaderReport .story-reader-note','#storyReaderReport .story-reader-limited','#storyReaderReport .story-reader-error','.story-reader-back','.ai-side-card h3','.side-title','.side-meta','.ai-translate-note','.ai-trust','.footer'];
function nodes(){const out=[];for(const sel of SELECTORS)document.querySelectorAll(sel).forEach(el=>{if(!el.isConnected)return;const txt=clean(el.textContent);if(bad(txt))return;if(!el.dataset.gnFinalOriginal&&english(txt))el.dataset.gnFinalOriginal=txt;if(el.dataset.gnFinalOriginal)out.push(el)});return [...new Set(out)]}
function restore(){for(const el of nodes()){const src=el.dataset.gnFinalOriginal;if(src&&clean(el.textContent)!==src)el.textContent=src;el.classList.remove('gn-i18n-pending');delete el.dataset.gnStatic}const q=document.querySelector('#q');if(q&&q.dataset.gnPlaceholderOriginal)q.placeholder=q.dataset.gnPlaceholderOriginal}
function applyStatic(to){const dict=STATIC[to]||{};for(const el of nodes()){const src=el.dataset.gnFinalOriginal;if(src&&dict[src]){el.textContent=dict[src];el.dataset.gnStatic='1'}}const q=document.querySelector('#q');if(q){if(!q.dataset.gnPlaceholderOriginal)q.dataset.gnPlaceholderOriginal=q.placeholder;const key=q.dataset.gnPlaceholderOriginal;if(to==='en')q.placeholder=key;else if(to==='hi')q.placeholder='वैश्विक खबरें, विषय, देश या स्रोत खोजें…';else if(to==='ur')q.placeholder='عالمی خبریں، موضوعات، ممالک یا ذرائع تلاش کریں…'}}
let generation=0,timer=0;
async function apply(){const g=++generation,to=lang();document.documentElement.lang=to;document.documentElement.dir=RTL.has(to)?'rtl':'ltr';restore();applyStatic(to);const main=document.getElementById('global-news-language-selector'),side=document.getElementById('aiStoryLanguage');if(main&&main.value!==to)main.value=to;if(side&&side.value!==to)side.value=to;if(to==='en')return;const all=nodes().filter(el=>!el.dataset.gnStatic);for(let i=0;i<all.length;i+=4){if(g!==generation||lang()!==to)return;await Promise.all(all.slice(i,i+4).map(async el=>{const src=el.dataset.gnFinalOriginal;if(!src)return;el.classList.add('gn-i18n-pending');const v=await translate(src,to);if(v&&g===generation&&lang()===to&&el.isConnected)el.textContent=v;el.classList.remove('gn-i18n-pending')}))}}
function schedule(ms=120){clearTimeout(timer);timer=setTimeout(apply,ms)}
function start(){theme();const q=document.querySelector('#q');if(q&&!q.dataset.gnPlaceholderOriginal)q.dataset.gnPlaceholderOriginal=q.placeholder;schedule(0);window.addEventListener('global-news-language-change',()=>schedule(0));new MutationObserver(ms=>{if(ms.some(m=>m.type==='childList'&&m.addedNodes.length))schedule(120)}).observe(document.body,{childList:true,subtree:true});window.addEventListener('storage',e=>{if(e.key===KEY)schedule(0)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();