(()=>{'use strict';
const KEY='globalNewsLanguage';
const LANG=[['en','English'],['hi','हिन्दी'],['bn','বাংলা'],['ur','اردو'],['zh','中文']];
const RTL=new Set(['ur']);
const T={en:{home:'Home',india:'India',world:'World',geo:'Geopolitics',rel:'International Relations',business:'Business',technology:'Technology',entertainment:'Entertainment',sports:'Sports',science:'Science',climate:'Climate',search:'Search',placeholder:'Search global stories, topics, countries or sources…',country:'Country',countryPlaceholder:'Search or select country…',explore:'🌍 Explore Worldwide',regions:'Regions & countries',back:'← Back to stories',brief:'Story Brief',report:'Full Report',sources:'Sources & attribution',read:'Read full story →'},hi:{home:'होम',india:'भारत',world:'विश्व',geo:'भू-राजनीति',rel:'अंतरराष्ट्रीय संबंध',business:'व्यापार',technology:'प्रौद्योगिकी',entertainment:'मनोरंजन',sports:'खेल',science:'विज्ञान',climate:'जलवायु',search:'खोजें',placeholder:'वैश्विक समाचार, विषय, देश या स्रोत खोजें…',country:'देश',countryPlaceholder:'देश खोजें या चुनें…',explore:'🌍 दुनिया भर में देखें',regions:'क्षेत्र और देश',back:'← खबरों पर वापस',brief:'समाचार सार',report:'विस्तृत रिपोर्ट',sources:'स्रोत और श्रेय',read:'पूरी खबर पढ़ें →'},bn:{home:'হোম',india:'ভারত',world:'বিশ্ব',geo:'ভূরাজনীতি',rel:'আন্তর্জাতিক সম্পর্ক',business:'ব্যবসা',technology:'প্রযুক্তি',entertainment:'বিনোদন',sports:'খেলাধুলা',science:'বিজ্ঞান',climate:'জলবায়ু',search:'অনুসন্ধান',placeholder:'বিশ্ব সংবাদ, বিষয়, দেশ বা উৎস খুঁজুন…',country:'দেশ',countryPlaceholder:'দেশ খুঁজুন বা নির্বাচন করুন…',explore:'🌍 বিশ্বজুড়ে দেখুন',regions:'অঞ্চল ও দেশ',back:'← সংবাদে ফিরে যান',brief:'সংবাদ সারাংশ',report:'বিস্তারিত প্রতিবেদন',sources:'উৎস ও স্বীকৃতি',read:'সম্পূর্ণ সংবাদ →'},ur:{home:'ہوم',india:'بھارت',world:'دنیا',geo:'جغرافیائی سیاست',rel:'بین الاقوامی تعلقات',business:'کاروبار',technology:'ٹیکنالوجی',entertainment:'تفریح',sports:'کھیل',science:'سائنس',climate:'آب و ہوا',search:'تلاش',placeholder:'عالمی خبریں، موضوعات، ممالک یا ذرائع تلاش کریں…',country:'ملک',countryPlaceholder:'ملک تلاش کریں یا منتخب کریں…',explore:'🌍 دنیا بھر میں دیکھیں',regions:'خطے اور ممالک',back:'→ خبروں پر واپس',brief:'خبر کا خلاصہ',report:'مکمل رپورٹ',sources:'ذرائع اور نسبت',read:'مکمل خبر پڑھیں ←'},zh:{home:'首页',india:'印度',world:'世界',geo:'地缘政治',rel:'国际关系',business:'商业',technology:'科技',entertainment:'娱乐',sports:'体育',science:'科学',climate:'气候',search:'搜索',placeholder:'搜索全球新闻、主题、国家或来源…',country:'国家',countryPlaceholder:'搜索或选择国家…',explore:'🌍 探索全球',regions:'地区和国家',back:'← 返回新闻',brief:'新闻摘要',report:'完整报道',sources:'来源与归属',read:'阅读全文 →'}};
function cleanLang(){const x=localStorage.getItem(KEY)||'en';return T[x]?x:'en'}
function theme(){if(document.getElementById('phase6a-tricolour'))return;const s=document.createElement('style');s.id='phase6a-tricolour';s.textContent=':root{--p6-s:#ff9933;--p6-g:#138808}.top{border-top:4px solid var(--p6-s)!important;border-bottom:4px solid var(--p6-g)!important}.navwrap{border-top:2px solid var(--p6-s)!important;border-bottom:2px solid var(--p6-g)!important}.nav .active{box-shadow:inset 0 3px var(--p6-s),inset 0 -3px var(--p6-g)!important}.hero,.story-card,.story-reader-card{border-top:3px solid var(--p6-s)!important;border-bottom:3px solid var(--p6-g)!important}.phase6a-language{margin-left:12px;height:36px;border:1px solid #475467;border-radius:9px;background:#172033;color:#fff;padding:0 10px;font-weight:700}.phase6a-language option{background:#fff;color:#101828}';document.head.appendChild(s)}
function selector(){if(document.getElementById('global-news-language-selector'))return;const top=document.querySelector('.top .bar');if(!top)return;const sel=document.createElement('select');sel.id='global-news-language-selector';sel.className='phase6a-language';sel.setAttribute('aria-label','Language');sel.innerHTML=LANG.map(([v,n])=>'<option value="'+v+'">'+n+'</option>').join('');sel.value=cleanLang();sel.addEventListener('change',()=>{localStorage.setItem(KEY,sel.value);applyLanguage();document.dispatchEvent(new CustomEvent('global-news-language-change',{detail:{language:sel.value}}));});top.appendChild(sel)}
function setText(el,text){if(el&&text!=null)el.textContent=text}
function applyLanguage(){const l=cleanLang(),t=T[l]||T.en;document.documentElement.lang=l;document.documentElement.dir=RTL.has(l)?'rtl':'ltr';const nav=[['home',t.home],['myCountryTab',null],['India',t.india],['World',t.world],['Geopolitics',t.geo],['International Relations',t.rel],['Business',t.business],['Technology',t.technology],['Entertainment',t.entertainment],['Sports',t.sports],['Science',t.science],['Climate',t.climate]];for(const [key,val] of nav){let el=key==='home'?document.querySelector('[data-mode="home"]'):key==='myCountryTab'?document.getElementById('myCountryTab'):[...document.querySelectorAll('[data-cat]')].find(x=>x.dataset.cat===key);if(val)setText(el,val)}const search=document.getElementById('search'),q=document.getElementById('q'),label=document.querySelector('.country-picker label'),cs=document.getElementById('countrySearch'),title=document.querySelector('.explorer-title'),sub=title&&title.querySelector('span');setText(search,t.search);if(q)q.placeholder=t.placeholder;setText(label,t.country);if(cs)cs.placeholder=t.countryPlaceholder;if(title){const span=sub;title.firstChild.textContent=t.explore+' ';if(span)span.textContent=t.regions}document.querySelectorAll('.story-reader-back,.back').forEach(x=>setText(x,t.back));document.querySelectorAll('.story-reader-section h2').forEach(x=>{const v=x.textContent.toLowerCase();if(v.includes('brief'))x.textContent=t.brief;else if(v.includes('report'))x.textContent=t.report;else if(v.includes('source'))x.textContent=t.sources});document.querySelectorAll('.read').forEach(x=>{if(/read full story|पूरी खबर|সম্পূর্ণ সংবাদ|مکمل خبر|阅读全文/i.test(x.textContent))x.textContent=t.read});const sel=document.getElementById('global-news-language-selector');if(sel)sel.value=l}
function countryValue(){const x=document.getElementById('countrySearch');return x?x.value.trim():''}
function syncCanonical(){const c=countryValue(),tab=document.getElementById('myCountryTab'),home=document.querySelector('[data-mode="home"]');if(c&&c!=='All'){if(tab)tab.textContent=c==='India'?'🇮🇳 '+(T[cleanLang()]||T.en).india:'▣ '+c;document.querySelectorAll('#nav button').forEach(x=>x.classList.remove('active'));if(tab)tab.classList.add('active')}else if(home&&!document.querySelector('[data-cat].active')){document.querySelectorAll('#nav button').forEach(x=>x.classList.remove('active'));home.classList.add('active')}}
function stateGuards(){document.addEventListener('click',e=>{const b=e.target.closest('#nav button');if(b){if(b.dataset.mode==='home'){setTimeout(()=>{const cs=document.getElementById('countrySearch');if(cs)cs.value='';syncCanonical()},0)}else if(b.dataset.cat){const cs=document.getElementById('countrySearch');if(cs)cs.value='';}}
const r=e.target.closest('#regions button');if(r){const cs=document.getElementById('countrySearch');if(cs)cs.value='';}
const opt=e.target.closest('.country-option');if(opt)setTimeout(syncCanonical,0)},true);const obs=new MutationObserver(()=>{selector();applyLanguage();syncCanonical()});obs.observe(document.body,{childList:true,subtree:true});setInterval(syncCanonical,350)}
function start(){theme();selector();applyLanguage();stateGuards()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start,{once:true});else start();
})();
