const { test, expect } = require('@playwright/test');
const stories=[
{id:'rich-story',headline:'Major agreement changes regional policy',summary:'Officials announced a major agreement after talks. The agreement sets a new timetable for implementation.',body:'Officials announced a major agreement after talks. The agreement sets a new timetable for implementation. Independent analysts said the implementation schedule will require additional funding and coordination. A second round of consultations is expected before the first deadline.',category:'World',country:'Global',verification_status:'verified',source_count:2,sources:[{publisher:'Source One'},{publisher:'Source Two'}]},
{id:'limited-story',headline:'Limited live update',summary:'The live feed currently contains only this short source update.',body:'',category:'World',country:'Global',verification_status:'developing',source_count:1},
{id:'malformed-story',headline:'Malformed <b>live</b> update',summary:'&lt;a href="https://example.test"&gt;Clean source update&lt;/a&gt; &amp; more context.',body:'',category:'World',country:'Global',verification_status:'developing',source_count:1}
];
async function mockFeed(page){await page.route('**/api/news**',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify(stories)}));}
async function openStory(page,id){await page.locator(`[data-open="${id}"]`).first().click();await expect(page.locator('#detail')).not.toHaveClass(/hidden/);}
function section(page,title){const h=page.getByRole('heading',{name:title,exact:true});return {heading:h,content:h.locator('xpath=following-sibling::*[1]')};}
test('rich story keeps Brief and Full Report materially distinct and source grounded',async({page})=>{await mockFeed(page);await page.goto('/');await openStory(page,'rich-story');const brief=section(page,'Story Brief'),report=section(page,'Full Report');await expect(brief.content).toContainText('Officials announced a major agreement');await expect(report.content).toContainText('Independent analysts said the implementation schedule');await expect(report.content).not.toContainText('Coverage is currently filed under');await expect(report.content).not.toContainText('source is represented in the live feed');await page.getByRole('button',{name:/Back to stories/i}).click();await expect(page.locator('#home')).not.toHaveClass(/hidden/);await expect(page.locator('[data-open="rich-story"]').first()).toBeVisible();});
test('limited-content story never duplicates summary or copies metadata into Full Report',async({page})=>{await mockFeed(page);await page.goto('/');await openStory(page,'limited-story');const brief=section(page,'Story Brief'),report=section(page,'Full Report');await expect(brief.content).toContainText('The live feed currently contains only this short source update.');await expect(report.content).toContainText('Additional source-grounded detail is not available');await expect(report.content).not.toContainText('Coverage is currently filed under');await expect(report.content).not.toContainText('source is represented in the live feed');});
test('malformed feed markup is decoded and never exposed as raw HTML in Story Reader',async({page})=>{await mockFeed(page);await page.goto('/');await openStory(page,'malformed-story');await expect(page.locator('#article h1')).toContainText('Malformed live update');await expect(page.locator('#article')).not.toContainText('&lt;a href');const brief=section(page,'Story Brief'),report=section(page,'Full Report');await expect(brief.content).toContainText('Clean source update & more context.');await expect(report.content).toContainText('Additional source-grounded detail is not available');});
