import { inferCountryFromStory } from "../lib/country-inference.js";
import { inferCategoryFromStory } from "../lib/category-inference.js";

const SUPABASE_URL=process.env.SUPABASE_URL||"https://nfqwnrmwyhcycjsfwqfl.supabase.co";
const SUPABASE_KEY=process.env.SUPABASE_ANON_KEY||"sb_publishable_FXSeGzRWwQ3FbyBWf_z80g_DHlcLcCl";
const GDELT_URL="https://api.gdeltproject.org/api/v2/doc/doc";
// Broad, non-overlapping topic coverage. The previous 10/3 query set was too narrow and
// could collapse to roughly 200 unique stories after URL/title deduplication.
const HOME_TOPICS=["world news","breaking world news","international news","India news","US news","Europe news","Asia news","Middle East news","Africa news","Latin America news","geopolitics","international relations","diplomacy","business news","global economy","markets","technology news","artificial intelligence","science news","climate change","environment news","health news","sports news","football news","cricket news","entertainment news","culture news","space news","energy news","conflict and security news"];
const GDELT_HOME_QUERIES=["world news","international news","breaking news","geopolitics","global economy","technology","science","climate change","sports","entertainment"];

function decodeEntities(value){return String(value||"").replace(/&#x([0-9a-f]+);?/gi,(_,hex)=>String.fromCodePoint(parseInt(hex,16))).replace(/&#([0-9]+);?/g,(_,num)=>String.fromCodePoint(parseInt(num,10))).replace(/&(amp|quot|apos|nbsp|#39|lt|gt);/gi,(_,name)=>({amp:"&",quot:'"',apos:"'",nbsp:" ","#39":"'",lt:"<",gt:">"}[name.toLowerCase()]||_));}
function clean(value){let out=String(value||"");for(let i=0;i<2;i++)out=decodeEntities(out).replace(/<[^>]*>/g," ");return decodeEntities(out).replace(/\s+/g," ").trim();}
const key=v=>clean(v).toLowerCase();
async function text(url,timeout=8000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{signal:c.signal,headers:{Accept:"application/xml,text/xml,text/html,application/json","User-Agent":"GlobalNewsPlatform/1.0"}});if(!r.ok)throw Error(`HTTP ${r.status}`);return await r.text()}finally{clearTimeout(t)}}
async function json(url,opts={},timeout=9000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{...opts,signal:c.signal});if(!r.ok)throw Error(`HTTP ${r.status}`);return await r.json()}finally{clearTimeout(t)}}
function normalize(s,requestedCategory){const cleaned={...s,headline:clean(s.headline),summary:clean(s.summary),body:clean(s.body),sources:Array.isArray(s.sources)?s.sources.map(x=>({...x,publisher:clean(x.publisher),title:clean(x.title)})):s.sources};const country=inferCountryFromStory(cleaned),cat=requestedCategory?{category:requestedCategory,inferred:false}:inferCategoryFromStory(cleaned);return {...cleaned,country:country.country||cleaned.country||"Global",category:cat.category||cleaned.category||"World",verification_status:cleaned.verification_status||"developing",source_count:Number(cleaned.source_count||1)}}
async function supabase(){const fields="id,slug,headline,summary,body,category,country,status,verification_status,source_count,published_at,created_at,updated_at";const u=`${SUPABASE_URL}/rest/v1/news_stories?status=in.(verified,published,corrected,developing)&select=${fields}&order=published_at.desc.nullslast,created_at.desc&limit=1000`;const rows=await json(u,{headers:{apikey:SUPABASE_KEY,Authorization:`Bearer ${SUPABASE_KEY}`,Accept:"application/json"}},12000);return Array.isArray(rows)?rows.map(x=>normalize(x)):[]}
function topic(category){return ({India:"India",World:"World",Geopolitics:"geopolitics",'International Relations':"international relations",Business:"business",Technology:"technology",Entertainment:"entertainment",Sports:"sports",Science:"science",Climate:"climate change"}[category]||"world news")}
function xmlTag(block,name){const m=block.match(new RegExp(`<${name}[^>]*>([\\s\\S]*?)<\\/${name}>`,`i`));return m?clean(m[1].replace(/^<!\[CDATA\[|\]\]>$/g,"")):""}
function xmlAttr(block,name){const m=block.match(new RegExp(`<${name}[^>]*href=["']([^"']+)["']`,`i`));return m?decodeEntities(m[1]):""}
function googleRows(xml,query,requestedCategory){const items=xml.match(/<item>[\s\S]*?<\/item>/gi)||[];return items.slice(0,100).map((b,i)=>normalize({id:`google:${query}:${i}:${key(xmlTag(b,"title")).replace(/[^a-z0-9]+/g,"-").slice(0,80)}`,headline:xmlTag(b,"title"),summary:xmlTag(b,"description"),body:xmlTag(b,"description"),published_at:xmlTag(b,"pubDate"),source:"Google News RSS",sources:[{publisher:xmlTag(b,"source")||"Google News",url:xmlTag(b,"link")||xmlAttr(b,"link"),title:xmlTag(b,"title")}],source_count:1},requestedCategory)).filter(x=>x.headline)}
async function google(req){const requested=typeof req.query?.category==="string"?req.query.category:null;const queries=requested?[topic(requested)]:HOME_TOPICS;const settled=await Promise.allSettled(queries.map(async q=>googleRows(await text(`https://news.google.com/rss/search?q=${encodeURIComponent(q)}&hl=en-IN&gl=IN&ceid=IN:en`,8000),q,requested)));return settled.flatMap(r=>r.status==="fulfilled"?r.value:[])}
async function gdeltQuery(q,requestedCategory){const u=new URL(GDELT_URL);u.searchParams.set("query",q);u.searchParams.set("mode","artlist");u.searchParams.set("format","json");u.searchParams.set("maxrecords","250");u.searchParams.set("sort","datedesc");const p=await json(u,{headers:{Accept:"application/json"}},9000);return Array.isArray(p?.articles)?p.articles.map((x,i)=>normalize({id:`gdelt:${q}:${i}:${key(x.url||x.title).replace(/[^a-z0-9]+/g,"-").slice(0,80)}`,headline:x.title,summary:x.seendate?`Live coverage indexed ${x.seendate}.`:"",body:"",published_at:x.seendate||null,source:"GDELT",sources:x.url?[{publisher:x.domain||"GDELT-indexed source",url:x.url,title:x.title}]:[],source_count:1},requestedCategory)).filter(x=>x.headline):[]}
async function gdelt(req){const requested=typeof req.query?.category==="string"?req.query.category:null;const queries=requested?[topic(requested)]:GDELT_HOME_QUERIES;const settled=await Promise.allSettled(queries.map(q=>gdeltQuery(q,requested)));return settled.flatMap(r=>r.status==="fulfilled"?r.value:[])}
function dedupe(rows){const seen=new Set();return rows.filter(x=>{const k=key(x.slug||x.sources?.[0]?.url||x.headline);if(!k||seen.has(k))return false;seen.add(k);return true})}
export default async function handler(req,res){res.setHeader("Cache-Control","no-store, no-cache, must-revalidate, max-age=0");if(req.method!=="GET")return res.status(405).json({error:"Method not allowed"});const id=typeof req.query?.id==="string"?req.query.id:null;if(id){try{const rows=await supabase();const row=rows.find(x=>String(x.id)===id);return row?res.status(200).json([row]):res.status(404).json({error:"Story not found"})}catch(e){return res.status(404).json({error:"Story not found"})}}
const requested=typeof req.query?.category==="string"?req.query.category:null;const results=await Promise.allSettled([supabase(),google(req),gdelt(req)]);const names=["supabase","google","gdelt"],diagnostics={};results.forEach((r,i)=>diagnostics[names[i]]=r.status==="fulfilled"?{ok:true,count:r.value.length}:{ok:false,error:r.reason?.message||"failed"});let rows=[];results.forEach(r=>{if(r.status==="fulfilled")rows.push(...r.value)});rows=dedupe(rows).filter(x=>!requested||key(x.category)===key(requested)).sort((a,b)=>new Date(b.published_at||0)-new Date(a.published_at||0));res.setHeader("X-News-Source-Count",String(rows.length));res.setHeader("X-News-Sources",names.filter((n,i)=>results[i].status==="fulfilled"&&results[i].value.length).join(",")||"none");res.setHeader("X-News-Diagnostics",Buffer.from(JSON.stringify(diagnostics)).toString("base64"));return res.status(200).json(rows)}