function clean(v){return String(v||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/\s+/g,' ').trim()}
function noise(v){const x=clean(v);return !x||/we can'?t connect to the server|too much traffic|cloudfront|request blocked|access denied|bad gateway|service unavailable|internal server error|request could not be satisfied|request id\s*[:=]/i.test(x)}
function decode(v){return clean(v).replace(/&#x([0-9a-f]+);?/gi,(_,h)=>String.fromCodePoint(parseInt(h,16))).replace(/&#([0-9]+);?/g,(_,n)=>String.fromCodePoint(parseInt(n,10)))}
function sentences(v){return decode(v).split(/(?<=[.!?])\s+(?=[A-Z0-9“"'])|\n+/).map(clean).filter(x=>x.length>=45&&!noise(x)&&!/^(follow|listen to|send your story|sign up|subscribe|read more|related|more on|watch|share|facebook|instagram|youtube)/i.test(x))}
function xml(s,t){const m=s.match(new RegExp(`<${t}[^>]*>([\\s\\S]*?)<\\/${t}>`,'i'));return m?decode(m[1].replace(/^<!\[CDATA\[|\]\]>$/g,'')):''}
async function get(url,ms=2600){const c=new AbortController(),tm=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{redirect:'follow',signal:c.signal,headers:{Accept:'text/html,application/xhtml+xml,text/plain,application/xml','User-Agent':'Mozilla/5.0 (compatible; GlobalNewsPlatform/6.3)'}});if(!r.ok)throw Error('HTTP '+r.status);return {text:await r.text(),url:r.url||url}}finally{clearTimeout(tm)}}
function meta(h,n){const q=n.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const a=new RegExp(`<meta[^>]+(?:name|property)=[\\"']${q}[\\"'][^>]+content=[\\"']([^\\"']+)[\\"']`,'i').exec(h);const b=new RegExp(`<meta[^>]+content=[\\"']([^\\"']+)[\\"'][^>]+(?:name|property)=[\\"']${q}[\\"']`,'i').exec(h);return clean(a?.[1]||b?.[1]||'')}
function pageTitle(h,f){return clean(meta(h,'og:title')||meta(h,'twitter:title')||/<title[^>]*>([\s\S]*?)<\/title>/i.exec(h)?.[1]||/<h1[^>]*>([\s\S]*?)<\/h1>/i.exec(h)?.[1]||f)}
function articleBodies(h){const out=[];for(const m of h.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{const walk=x=>{if(!x)return;if(Array.isArray(x)){x.forEach(walk);return}if(typeof x==='object'){if(typeof x.articleBody==='string'&&clean(x.articleBody).length>=180)out.push(clean(x.articleBody));if(x['@graph'])walk(x['@graph'])}};walk(JSON.parse(m[1]))}catch{}}return [...new Set(out)]}
function extractParagraphs(h){const out=[];for(const m of h.matchAll(/<p\b[^>]*>([\s\S]*?)<\/p>/gi)){const x=clean(m[1]);if(x.length>=70&&x.length<=2500&&!noise(x)&&!/cookie|subscribe|newsletter|privacy policy|terms of use|all rights reserved|sign up|follow .* on (facebook|instagram|twitter|x\b)/i.test(x))out.push(x)}return [...new Set(out)]}
function extract(h){const bodies=articleBodies(h);if(bodies.length){const body=bodies.sort((a,b)=>b.length-a.length)[0];return sentences(body)}return extractParagraphs(h).flatMap(sentences)}
function markdown(t){return String(t||'').split(/\n\s*\n+/).map(x=>x.replace(/^#{1,6}\s*/g,'').replace(/^[*-+]\s+/g,'').replace(/\[[^\]]+\]\([^)]*\)/g,'').replace(/\s+/g,' ').trim()).filter(x=>x.length>=70&&!noise(x)&&!/cookie|subscribe|newsletter|privacy policy|terms of use|all rights reserved|sign up|follow .* on (facebook|instagram|twitter|x\b)|related stories|more on this story/i.test(x))}
async function readDirect(u,h){try{const r=await get(u,2400);if(noise(r.text))return null;const t=pageTitle(r.text,h),d=meta(r.text,'description')||meta(r.text,'og:description'),p=extract(r.text);const good=[...new Set(p)].filter(x=>x.length>=70&&!noise(x));if(d.length>=80&&!noise(d)&&!good.some(x=>x.toLowerCase()===d.toLowerCase()))good.unshift(d);return good.length>=2?{blocks:good.slice(0,24),url:r.url||u,title:t,excerpt:d||good[0],method:'direct-html'}:null}catch{return null}}
async function readJina(u,h){try{const r=await get('https://r.jina.ai/'+u,3000);if(noise(r.text))return null;const p=markdown(r.text);return p.length>=2?{blocks:p.slice(0,24),url:u,title:h,excerpt:p[0],method:'jina-reader'}:null}catch{return null}}
async function resolve(u){u=clean(u);if(!u||!/news\.google\.com/i.test(u))return u;try{const r=await get(u,1800);if(r.url&&!/news\.google\.com/i.test(r.url))return r.url;const m=/<link[^>]+rel=["']canonical["'][^>]+href=["']([^"']+)["']/i.exec(r.text)||/<meta[^>]+property=["']og:url["'][^>]+content=["']([^"']+)["']/i.exec(r.text);return clean(m?.[1]||u)}catch{return u}}
async function rss(h){try{const r=await get('https://news.google.com/rss/search?q='+encodeURIComponent('"'+h+'"')+'&hl=en-IN&gl=IN&ceid=IN:en',2200);const items=r.text.match(/<item>[\s\S]*?<\/item>/gi)||[];return items.slice(0,5).map(x=>({title:xml(x,'title'),url:xml(x,'link'),publisher:xml(x,'source'),excerpt:xml(x,'description')})).filter(x=>x.url)}catch{return []}}
function build(raw,summary,h){const all=[...new Set(raw.flatMap(sentences))],hl=clean(h).toLowerCase(),brief=[],used=new Set();for(const s of all){const k=s.toLowerCase();if(k===hl||used.has(k))continue;brief.push(s);used.add(k);if(brief.length>=6)break}for(const s of sentences(summary)){const k=s.toLowerCase();if(k===hl||used.has(k))continue;brief.push(s);used.add(k);if(brief.length>=6)break}const briefSet=new Set(brief.map(x=>x.toLowerCase())),report=[];for(const s of all){if(briefSet.has(s.toLowerCase()))continue;const k=s.toLowerCase();if(report.some(x=>x.toLowerCase()===k))continue;report.push(s);if(report.length>=8)break}if(report.length<2){for(let i=0;i<all.length;i+=2){const p=clean(all.slice(i,i+2).filter(x=>!briefSet.has(x.toLowerCase())).join(' '));if(p.length>=100)report.push(p);if(report.length>=6)break}}return {brief:[...new Set(brief)].slice(0,6),report:[...new Set(report)].slice(0,8)}}
function sourceObj(h,summary,src,primary,got){return {url:got?.url||primary||src?.url||'',publisher:got?.publisher||src?.publisher||'Source',title:got?.title||h,excerpt:got?.excerpt||summary}}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store, no-cache, must-revalidate, max-age=0');res.setHeader('CDN-Cache-Control','no-store');res.setHeader('Vercel-CDN-Cache-Control','no-store');if(req.method!=='POST')return res.status(405).json({ok:false,error:'Method not allowed'});const s=req.body?.story||{},h=clean(s.headline||s.title),summary=clean(s.summary||s.description),src=(Array.isArray(s.sources)?s.sources:[]).map(x=>({url:clean(x?.url||x?.link),title:clean(x?.title||h),publisher:clean(x?.publisher||x?.domain||'Source'),excerpt:clean(x?.excerpt)})).find(x=>x.url)||null;if(!h)return res.status(400).json({ok:false,error:'headline_required'});let primary='',got=null;try{primary=src?.url?await resolve(src.url):'';if(primary){const [a,b]=await Promise.all([readDirect(primary,h),readJina(primary,h)]);got=a&&b?(a.blocks.length>=b.blocks.length?a:b):(a||b)}const candidates=got?[]:await rss(h);if(!got){for(const c of candidates.slice(0,2)){const u=await resolve(c.url);if(!u||/news\.google\.com/i.test(u))continue;const [a,b]=await Promise.all([readDirect(u,c.title||h),readJina(u,c.title||h)]);const r=a&&b?(a.blocks.length>=b.blocks.length?a:b):(a||b);if(r){got={...r,publisher:c.publisher||'Publisher'};break}}}if(!got&&candidates.length){const snippets=candidates.map(x=>clean(x.excerpt)).filter(x=>x.length>=100&&!noise(x));if(snippets.length>=2)got={blocks:snippets.slice(0,6),url:candidates[0]?.url||primary||'',title:candidates[0]?.title||h,publisher:candidates[0]?.publisher||src?.publisher||'Source',excerpt:snippets[0],method:'rss-snippet'}}if(!got)return res.status(200).json({ok:false,error:'source_unavailable',brief:{points:[]},report:{label:'Source-grounded full report',paragraphs:[]},source:sourceObj(h,summary,src,primary,null),retrieval:{status:'unavailable'}});const x=build(got.blocks,summary,h);const ok=x.brief.length>=2&&x.report.length>=2;return res.status(200).json({ok,error:ok?null:'insufficient_distinct_publisher_text',brief:{points:x.brief,coverage:'Key takeaways extracted from retrieved publisher or syndicated source material.'},report:{label:'Source-grounded full report',paragraphs:x.report,coverage:'Full Report uses retrieved publisher article text and remains separate from Story Brief.'},source:sourceObj(h,summary,src,primary,got),retrieval:{status:ok?'success':'insufficient',method:got.method||'retrieval'}})}catch(e){console.error('story-content failed',e?.message||e);return res.status(200).json({ok:false,error:'story_content_retrieval_failed',brief:{points:[]},report:{label:'Source-grounded full report',paragraphs:[]},source:sourceObj(h,summary,src,primary,got),retrieval:{status:'error'}})}}