function clean(value){return String(value||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'\"').replace(/&#39;/gi,"'").replace(/\s+/g,' ').trim()}
function decode(value){return clean(value).replace(/&#x([0-9a-f]+);?/gi,(_,h)=>String.fromCodePoint(parseInt(h,16))).replace(/&#([0-9]+);?/g,(_,n)=>String.fromCodePoint(parseInt(n,10)))}
function sentences(value){return decode(value).split(/(?<=[.!?])\s+(?=[A-Z0-9“\"'])|\n+/).map(clean).filter(x=>x.length>=55)}
function xml(text,tag){const m=text.match(new RegExp(`<${tag}[^>]*>([\\s\\S]*?)<\\/${tag}>`,'i'));return m?decode(m[1].replace(/^<!\[CDATA\[|\]\]>$/g,'')):''}
async function get(url,timeout){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeout||7000);try{const r=await fetch(url,{redirect:'follow',signal:controller.signal,headers:{Accept:'text/html,application/xhtml+xml,text/plain,application/xml','User-Agent':'Mozilla/5.0 (compatible; GlobalNewsPlatform/4.0)'}});if(!r.ok)throw Error(String(r.status));return {text:await r.text(),url:r.url||url}}finally{clearTimeout(timer)}}
function meta(html,name){const n=name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const a=new RegExp(`<meta[^>]+(?:name|property)=[\"']${n}[\"'][^>]+content=[\"']([^\"']+)[\"'][^>]*>`,'i').exec(html);const b=new RegExp(`<meta[^>]+content=[\"']([^\"']+)[\"'][^>]+(?:name|property)=[\"']${n}[\"'][^>]*>`,'i').exec(html);return clean(a?.[1]||b?.[1]||'')}
function pageTitle(html,fallback){return clean(meta(html,'og:title')||meta(html,'twitter:title')||/<title[^>]*>([\s\S]*?)<\/title>/i.exec(html)?.[1]||/<h1[^>]*>([\s\S]*?)<\/h1>/i.exec(html)?.[1]||fallback)}
function relevant(page,story){const a=new Set(page.toLowerCase().replace(/[^a-z0-9\s]/g,' ').split(/\s+/).filter(x=>x.length>3)),b=story.toLowerCase().replace(/[^a-z0-9\s]/g,' ').split(/\s+/).filter(x=>x.length>3);const overlap=b.filter(x=>a.has(x)).length;return overlap>=3||overlap/Math.max(1,b.length)>=.25}
function extract(html){const out=[];for(const m of html.matchAll(/<p\b[^>]*>([\s\S]*?)<\/p>/gi)){const x=clean(m[1]);if(x.length>=70&&x.length<=2600)out.push(x)}for(const m of html.matchAll(/<script[^>]+type=[\"']application\/ld\+json[\"'][^>]*>([\s\S]*?)<\/script>/gi)){try{const walk=x=>{if(!x)return;if(Array.isArray(x)){x.forEach(walk);return}if(typeof x==='object'){if(typeof x.articleBody==='string')out.push(clean(x.articleBody));Object.values(x).forEach(walk)}};walk(JSON.parse(m[1]))}catch{}}return [...new Set(out)]}
async function direct(url,title){try{const r=await get(url,7000);const pt=pageTitle(r.text,title);if(!relevant(pt,title))return null;const blocks=extract(r.text);if(blocks.length>=3)return {blocks:blocks.slice(0,24),url:r.url||url,title:pt,publisher:'Publisher',method:'direct-html'}}catch{}return null}
async function jina(url,title){try{const r=await get('https://r.jina.ai/'+url,9000);const blocks=String(r.text||'').split(/\n\s*\n+/).map(clean).filter(x=>x.length>=70&&!/cookie|subscribe|newsletter|privacy policy|terms of use|all rights reserved|sign up/i.test(x));if(blocks.length>=3)return {blocks:blocks.slice(0,24),url,title,publisher:'Publisher',method:'jina-reader'}}catch{}return null}
async function googleAlternates(headline){try{const r=await get('https://news.google.com/rss/search?q='+encodeURIComponent('"'+headline+'"')+'&hl=en-IN&gl=IN&ceid=IN:en',7000);const items=r.text.match(/<item>[\s\S]*?<\/item>/gi)||[];return items.slice(0,10).map(x=>({title:xml(x,'title'),url:xml(x,'link'),publisher:xml(x,'source'),description:xml(x,'description')})).filter(x=>x.url)}catch{return []}}
async function gdeltAlternates(headline){try{const r=await get('https://api.gdeltproject.org/api/v2/doc/doc?query='+encodeURIComponent(headline)+'&mode=artlist&format=json&maxrecords=12&sort=datedesc',7000);const data=JSON.parse(r.text);return Array.isArray(data?.articles)?data.articles.map(x=>({title:clean(x.title),url:clean(x.url),publisher:clean(x.domain||x.source||'Publisher')})).filter(x=>x.url&&x.title):[]}catch{return []}}
async function retrieve(primary,title){if(primary){const [a,b]=await Promise.all([direct(primary,title),jina(primary,title)]);if(a&&b)return a.blocks.length>=b.blocks.length?a:b;if(a||b)return a||b}const candidates=[...(await gdeltAlternates(title)),...(await googleAlternates(title))];for(const c of candidates.slice(0,8)){const got=await jina(c.url,c.title||title);if(got)return {...got,publisher:c.publisher||'Publisher'}}return null}
function unique(values){return [...new Set(values.map(clean).filter(Boolean))]}
function briefFrom(report,summary,headline){const h=clean(headline).toLowerCase(),out=[];for(const p of report){for(const s of sentences(p)){if(s.toLowerCase()===h)continue;if(!out.some(x=>x.toLowerCase()===s.toLowerCase()))out.push(s);if(out.length===6)break}if(out.length===6)break}for(const s of sentences(summary)){if(s.toLowerCase()!==h&&!out.some(x=>x.toLowerCase()===s.toLowerCase()))out.push(s);if(out.length===6)break}return out.slice(0,6)}
function reportWithoutBrief(report,brief){const used=new Set(brief.map(x=>clean(x).toLowerCase()));return report.map(p=>sentences(p).filter(x=>!used.has(x.toLowerCase())).join(' ')).filter(x=>x.length>=90).slice(0,12)}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store, no-cache, must-revalidate, max-age=0');if(req.method!=='POST')return res.status(405).json({ok:false,error:'method_not_allowed'});try{const story=req.body?.story||{},headline=clean(story.headline||story.title),summary=clean(story.summary||story.description),body=clean(story.body);if(!headline)return res.status(400).json({ok:false,error:'headline_required'});const primary=(Array.isArray(story.sources)?story.sources:[]).map(x=>({url:clean(x?.url||x?.link),title:clean(x?.title||headline),publisher:clean(x?.publisher||x?.domain||'Source')})).find(x=>x.url);let got=primary?await retrieve(primary.url,primary.title||headline):null;if(!got)got=await retrieve('',headline);let raw=got?unique(got.blocks):[];if(raw.length<3&&body){const bodyBlocks=sentences(body);if(bodyBlocks.length>=3)raw=bodyBlocks}const expanded=unique(raw.flatMap(sentences));const brief=briefFrom(expanded,summary,headline);const report=reportWithoutBrief(expanded,brief);if(brief.length<4||report.length<3)return res.status(200).json({ok:false,error:'insufficient_source_content',brief:{points:brief},report:{paragraphs:report},source:got?{url:got.url,publisher:got.publisher,title:got.title}:null});return res.status(200).json({ok:true,brief:{points:brief,coverage:'Key takeaways extracted from retrieved publisher material.'},report:{label:'Source-grounded full report',paragraphs:report,coverage:'Full Report is assembled from retrieved publisher or syndicated publisher material and kept separate from the Story Brief.'},source:got?{url:got.url,publisher:got.publisher,title:got.title}:null,retrieval:{method:got?.method||'feed-body',sentence_count:expanded.length}})}catch(e){return res.status(200).json({ok:false,error:'story_content_retrieval_failed'})}}