function clean(value){return String(value||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;/gi,' ').replace(/&amp;/gi,'&').replace(/&quot;/gi,'"').replace(/&#39;/gi,"'").replace(/\s+/g,' ').trim()}
function decode(value){return clean(value).replace(/&#x([0-9a-f]+);?/gi,(_,h)=>String.fromCodePoint(parseInt(h,16))).replace(/&#([0-9]+);?/g,(_,n)=>String.fromCodePoint(parseInt(n,10)))}
function sentences(value){const t=decode(value);return t.split(/(?<=[.!?])\s+(?=[A-Z0-9“"'])|\n+/).map(clean).filter(x=>x.length>=55)}
function extractXml(xml,tag){const m=xml.match(new RegExp(`<${tag}[^>]*>([\\s\\S]*?)<\\/${tag}>`,'i'));return m?decode(m[1].replace(/^<!\[CDATA\[|\]\]>$/g,'')):''}
async function fetchText(url,timeout=7000){const c=new AbortController(),timer=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(url,{redirect:'follow',signal:c.signal,headers:{Accept:'text/html,application/xhtml+xml,text/plain,application/xml','User-Agent':'Mozilla/5.0 (compatible; GlobalNewsPlatform/3.0)'}});if(!r.ok)throw Error(`HTTP ${r.status}`);return {text:await r.text(),url:r.url||url}}finally{clearTimeout(timer)}}
function titleTokens(v){return [...new Set(decode(v).toLowerCase().replace(/[^a-z0-9\s]/g,' ').split(/\s+/).filter(x=>x.length>=3))]}
function relevant(pageTitle,storyTitle){const a=new Set(titleTokens(pageTitle)),b=titleTokens(storyTitle);if(!b.length)return false;const overlap=b.filter(x=>a.has(x)).length;return overlap>=3||overlap/b.length>=0.30||(b.length<=12&&overlap>=2)}
function paragraphs(html){const out=[];for(const m of html.matchAll(/<p\b[^>]*>([\s\S]*?)<\/p>/gi)){const x=clean(m[1]);if(x.length>=70&&x.length<=2200)out.push(x)}return [...new Set(out)]}
function jsonLd(html){const out=[];for(const m of html.matchAll(/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi)){try{const walk=x=>{if(!x)return;if(Array.isArray(x)){x.forEach(walk);return}if(typeof x==='object'){if(typeof x.articleBody==='string')out.push(clean(x.articleBody));Object.values(x).forEach(walk)}};walk(JSON.parse(m[1]))}catch{}}return out}
function meta(html,name){const n=name.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const a=new RegExp(`<meta[^>]+(?:name|property)=[\\"']${n}[\\"'][^>]+content=[\\"']([^\\"']+)[\\"'][^>]*>`,'i').exec(html);const b=new RegExp(`<meta[^>]+content=[\\"']([^\\"']+)[\\"'][^>]+(?:name|property)=[\\"']${n}[\\"'][^>]*>`,'i').exec(html);return clean(a?.[1]||b?.[1]||'')}
function pageTitle(html,fallback){return clean(meta(html,'og:title')||meta(html,'twitter:title')||/<title[^>]*>([\s\S]*?)<\/title>/i.exec(html)?.[1]||/<h1[^>]*>([\s\S]*?)<\/h1>/i.exec(html)?.[1]||fallback)}
function markdownBlocks(text){return String(text||'').split(/\n\s*\n+/).map(x=>x.replace(/^#{1,6}\s*/g,'').replace(/^[*-+]\s+/g,'').replace(/\[[^\]]+\]\([^)]*\)/g,'').replace(/\s+/g,' ').trim()).filter(x=>x.length>=70&&!/cookie|subscribe|newsletter|privacy policy|terms of use|all rights reserved|sign up/i.test(x))}
async function jina(url,title){try{const r=await fetchText(`https://r.jina.ai/${url}`,8000);const text=r.text||'';const cleanTitle=pageTitle(text,title);const blocks=markdownBlocks(text);const body=blocks.filter(x=>x.length>=70);if(body.length>=1)return {blocks:body.slice(0,18),resolved:url,method:'jina-reader',title:cleanTitle,excerpt:body[0]||''}}catch{}return null}
async function direct(url,title){try{const r=await fetchText(url,6500);const pt=pageTitle(r.text,title);if(!relevant(pt,title))return null;const blocks=[...jsonLd(r.text),...paragraphs(r.text)];if(blocks.length>=1)return {blocks:blocks.slice(0,18),resolved:r.url||url,method:'direct-html',title:pt,excerpt:meta(r.text,'description')||meta(r.text,'og:description')||''}}catch{}return null}
async function googleAlternates(headline){try{const r=await fetchText(`https://news.google.com/rss/search?q=${encodeURIComponent(`"${headline}"`)}&hl=en-IN&gl=IN&ceid=IN:en`,6000);const items=r.text.match(/<item>[\s\S]*?<\/item>/gi)||[];return items.slice(0,8).map(x=>({title:extractXml(x,'title'),url:extractXml(x,'link'),publisher:extractXml(x,'source')})).filter(x=>x.url)}catch{return []}}
async function gdeltAlternates(headline){try{const r=await fetchText(`https://api.gdeltproject.org/api/v2/doc/doc?query=${encodeURIComponent(headline)}&mode=artlist&format=json&maxrecords=12&sort=datedesc`,6000);const data=JSON.parse(r.text);return Array.isArray(data?.articles)?data.articles.map(x=>({title:clean(x.title),url:clean(x.url),publisher:clean(x.domain||x.source||'Publisher')})).filter(x=>x.url&&x.title):[]}catch{return []}}
async function retrieve(url,title){
const attempts=[];
if(url){
  const [a,b]=await Promise.all([jina(url,title),direct(url,title)]);
  if(a&&b)return a.blocks.length>=b.blocks.length?a:b;
  if(a||b)return a||b;
  attempts.push(url);
}
const [discovery,google]=await Promise.all([gdeltAlternates(title),googleAlternates(title)]);
const candidates=[...discovery,...google].filter(x=>x.url&&!attempts.includes(x.url)).slice(0,6);
const settled=await Promise.allSettled(candidates.map(alt=>jina(alt.url,alt.title||title).then(got=>got?{...got,publisher:alt.publisher||'Publisher'}:null)));
for(const item of settled){
  if(item.status==='fulfilled'&&item.value?.blocks?.length)return item.value;
}
return {blocks:[],resolved:url||'',method:'unavailable',title,excerpt:''}
}
function unique(arr){return [...new Set(arr.map(clean).filter(Boolean))]}
function makeBrief(report,summary,headline){const out=[];const h=clean(headline).toLowerCase();for(const p of report){for(const s of sentences(p)){if(s.toLowerCase()===h)continue;if(!out.some(x=>x.toLowerCase()===s.toLowerCase()))out.push(s);if(out.length>=6)break}if(out.length>=6)break}for(const s of sentences(summary)){if(s.toLowerCase()===h)continue;if(!out.some(x=>x.toLowerCase()===s.toLowerCase()))out.push(s);if(out.length>=6)break}return out.slice(0,6)}
function reportWithoutBrief(report,points){const used=new Set(points.map(x=>clean(x).toLowerCase()));const out=[];for(const p of report){const remaining=sentences(p).filter(s=>!used.has(clean(s).toLowerCase())).join(' ');if(remaining.length>=70)out.push(remaining);else if(clean(p).length>=120&&!out.some(x=>x.toLowerCase()===clean(p).toLowerCase()))out.push(clean(p));if(out.length>=12)break}return out}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store, no-cache, must-revalidate, max-age=0');if(req.method!=='POST')return res.status(405).json({ok:false,error:'Method not allowed'});try{const story=req.body?.story||{};const headline=clean(story.headline||story.title);const summary=clean(story.summary||story.description);const sources=Array.isArray(story.sources)?story.sources:[];if(!headline)return res.status(400).json({ok:false,error:'headline_required'});let report=[];let chosen=null;const primary=sources.map(s=>({url:clean(s?.url||s?.link),publisher:clean(s?.publisher||s?.domain||'Source'),title:clean(s?.title||headline)})).filter(x=>x.url)[0];if(primary){const r=await retrieve(primary.url,primary.title||headline);if(r.blocks.length>=1){report=unique(r.blocks);chosen={url:r.resolved||primary.url,publisher:r.publisher||primary.publisher,title:r.title||primary.title,excerpt:r.excerpt||''}}}if(report.length<2){const r=await retrieve('',headline);if(r.blocks.length>=1){report=unique(r.blocks);chosen={url:r.resolved,publisher:r.publisher||'Publisher',title:r.title||headline,excerpt:r.excerpt||''}}}const expanded=unique(report.flatMap(x=>sentences(x)));const brief=makeBrief(expanded,summary,headline);const used=new Set(brief.map(x=>clean(x).toLowerCase()));const remaining=expanded.filter(x=>!used.has(clean(x).toLowerCase()));const grouped=[];for(let i=0;i<remaining.length;i+=2){const p=clean(remaining.slice(i,i+2).join(' '));if(p.length>=70)grouped.push(p)}let displayReport=unique(grouped).slice(0,12);if(displayReport.length<2){const distinct=reportWithoutBrief(report,brief);displayReport=unique([...displayReport,...distinct]).slice(0,12)}if(brief.length<2||displayReport.length<2){if(summary.length>=80){const partialReport=displayReport.length?displayReport:[summary];return res.status(200).json({ok:true,partial:true,error:'limited_publisher_text',brief:{points:brief},report:{label:'Available source detail',paragraphs:partialReport,coverage:'Only the source detail safely available from the live feed is shown; no additional article text was invented.'},source:chosen});}return res.status(200).json({ok:false,error:'insufficient_distinct_publisher_text',brief:{points:brief},report:{paragraphs:displayReport},source:chosen});}return res.status(200).json({ok:true,brief:{points:brief.slice(0,6),coverage:'Key takeaways extracted from retrieved publisher or syndicated publisher material.'},report:{label:'Source-grounded full report',paragraphs:displayReport,coverage:'The full report is assembled from publisher text after removing Story Brief sentences, so the two sections do not repeat each other.'},source:chosen,retrieval:{status:'success',sentence_count:expanded.length}})}catch(e){return res.status(200).json({ok:false,error:'story_content_retrieval_failed'})}}